# You can use any of these parameters to create conditions or mappings in your template.
Parameters:
  App:
    Type: String
    Description: iloveconference
  Env:
    Type: String
    Description: prod
  Name:
    Type: String
    Description: client-server

Resources:
  CWAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
            Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: "*"

Outputs:
  # 1. You need to output the IAM ManagedPolicy so that Copilot can add it as a managed policy to your ECS task role.
  CWAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref CWAccessPolicy
